run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - copyloopvar
    - revive
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - staticcheck
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - fieldalignment
  
  gocyclo:
    min-complexity: 40
  
  misspell:
    locale: US
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  
  funlen:
    lines: 100
    statements: 60
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/eddiefleurent/scranton_strangler

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
    
    - path: cmd/
      linters:
        - gochecknoinits
    
    - path: scripts/
      linters:
        - gocyclo
        - funlen
        
    - path: internal/config/config_test\.go
      linters:
        - gosec
    
    - path: internal/config/config\.go
      linters:
        - gosec  # G304 is a false positive, configPath is validated
    
    - path: internal/storage/mock_storage\.go
      linters:
        - gosec
    
    - path: internal/storage/storage\.go
      linters:
        - gosec  # G301 is acceptable for directory permissions
        - revive  # StorageData stuttering is acceptable
    
    - path: internal/storage/storage_test\.go
      linters:
        - gosec
    
    - path: internal/storage/interface\.go
      text: "stutters"
      linters:
        - revive
    
    - path: internal/mock/mock_data\.go  
      text: "stutters"
      linters:
        - revive
    
    - path: internal/strategy/strangle\.go
      text: "stutters"
      linters:
        - revive
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0