run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - copyloopvar
    - revive
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - goprintffuncname
    - gosec
    - gosimple
    - staticcheck
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - fieldalignment
  
  gocyclo:
    min-complexity: 45
  
  misspell:
    locale: US
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  
  funlen:
    lines: 100
    statements: 65
  
  goimports:
    local-prefixes: github.com/eddiefleurent/scranton_strangler
  
  gofmt:
    simplify: true
  
  gosec:
    excludes:
      - G301  # Poor file permissions
      - G304  # Potential file inclusion
  
  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - disableStutteringCheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo

    - path: cmd/
      linters:
        - gochecknoinits
        - funlen

    - path: scripts/
      linters:
        - gocyclo
        - funlen
        - revive

    - path: internal/config/config_test\.go
      linters:
        - gosec

    - path: internal/config/config\.go
      linters:
        - gosec

    - path: internal/storage/
      linters:
        - gosec
        - revive

    - path: internal/mock/
      linters:
        - revive

    - path: internal/strategy/
      linters:
        - revive
    
    - path: internal/orders/
      linters:
        - funlen
    
    - path: internal/retry/
      linters:
        - funlen
    
    - path: internal/broker/
      linters:
        - funlen