version: '3.8'

# Production overrides for docker-compose.yml
services:
  strangle-bot:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    environment:
      - CONFIG_PATH=/config.yaml
      - TZ=America/New_York
      - LOG_LEVEL=info
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "/strangle-bot", "--health-check"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s

  redis:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    command: redis-server --appendonly yes --save 900 1 --save 300 10 --save 60 10000