version: '3.8'

services:
  strangle-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strangle-bot
    restart: unless-stopped
    volumes:
      - ./config.yaml:/config.yaml:ro
      - ./data:/data:rw
      - ./logs:/logs:rw
    environment:
      - CONFIG_PATH=/config.yaml
      - TZ=America/New_York
    networks:
      - trading-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "/strangle-bot", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: trading-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - trading-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  trading-network:
    driver: bridge

volumes:
  redis-data:
    driver: local