name: CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Check Go version
        run: go version

      - name: Run tests with coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Display coverage report
        run: go tool cover -func=coverage.out

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Check Go version
        run: go version

      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@v2.22.0

      - name: Run Gosec (tolerate findings)
        continue-on-error: true
        run: |
          set -euo pipefail
          gosec -fmt sarif -out gosec-results.sarif ./...
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: gosec-results.sarif

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Check Go version
        run: go version

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.4.0
          args: --timeout=5m

